/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameSessionView = IDL.Record({
  'id' : IDL.Text,
  'territoryOwnership' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal)),
  'owner' : IDL.Principal,
  'unitPositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal)),
});

export const idlService = IDL.Service({
  'createGameSession' : IDL.Func([IDL.Text], [], []),
  'getAllGameSessions' : IDL.Func([], [IDL.Vec(GameSessionView)], ['query']),
  'getGameSession' : IDL.Func([IDL.Text], [GameSessionView], ['query']),
  'updateTerritoryOwnership' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateUnitPosition' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameSessionView = IDL.Record({
    'id' : IDL.Text,
    'territoryOwnership' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal)),
    'owner' : IDL.Principal,
    'unitPositions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal)),
  });
  
  return IDL.Service({
    'createGameSession' : IDL.Func([IDL.Text], [], []),
    'getAllGameSessions' : IDL.Func([], [IDL.Vec(GameSessionView)], ['query']),
    'getGameSession' : IDL.Func([IDL.Text], [GameSessionView], ['query']),
    'updateTerritoryOwnership' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateUnitPosition' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };